import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/providers/app-providers";
import { WalletConnectButton } from "@/components/WalletConnectButton";
import { UnifiedConnectModal } from "@/components/UnifiedConnectModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-6xl mx-auto px-4 py-6">
          <header className="mb-6 flex items-center justify-between">
            <h1 className="text-lg font-semibold">LUTAR Presale</h1>
            <AppProviders>
              <WalletConnectButton />
              <UnifiedConnectModal />
            </AppProviders>
          </header>
          <AppProviders>
            {children}
          </AppProviders>
        </div>
      </body>
    </html>
  );
}
